update init script

diff --git a/.init b/.init
--- a/.init
+++ b/.init
@@ -7,215 +7,180 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-if [ -z "$1" ]; then
+ALL=true
+
+while [[ $# -gt 0 ]]
+do
+key="$1"
+
+case $key in
+    --system)
+    SYSTEM=true
+    ALL=false
+    shift # past argument
+    ;;
+    --gui)
+    GUI=true
+    ALL=false
+    shift # past argument
+    ;;
+    *)    # unknown option
+    EMAIL="$1"
+    shift # past argument
+    ;;
+esac
+done
+
+if [ -z "$EMAIL" ]; then
     echo "please provide an email address as an argument"
     exit 1
 fi
 
-EMAIL="$1"
+cd $HOME
 
 # ==============================================
 # homebrew
 # ==============================================
 
-command -v brew >/dev/null 2>&1 || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if [ "$ALL" == true ] ; then
+  command -v brew >/dev/null 2>&1 || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 
-brew tap doodzik/tap
-# for screen
-brew tap homebrew/dupes 
-brew tap caskroom/cask
+  brew tap doodzik/tap
+  # for screen
+  brew tap homebrew/dupes 
+  brew tap caskroom/cask
 
-cmds=(
-  git
-  git-lfs
-  ghi
-  googler
-  m-cli
-  nvm
-  npm-scripts
-  note
-  screen
-  tidy-html5
-  yarn
-  youtube-dl
-  zsh
-  fzf
-  the_silver_searcher
-)
+  cmds=(
+    bash_join
+    fzf
+    git
+    git-lfs
+    m-cli
+    note
+    npm-scripts
+    nvm
+    the_silver_searcher
+    tidy-html5
+    yarn
+    youtube-dl
+    zsh
+  )
 
+  # install ruby
+  brew install rbenv 
+  LATEST_RUBY=$(rbenv install -l | sed -n '/^[[:space:]]*[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}[[:space:]]*$/ h;${g;p;}')
+  rbenv install $LATEST_RUBY 
+  rbenv rehash
+  rbenv global $LATEST_RUBY 
 
-# install ruby
-brew install rbenv 
-LATEST_RUBY=$(rbenv install -l | sed -n '/^[[:space:]]*[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}[[:space:]]*$/ h;${g;p;}')
-rbenv install $LATEST_RUBY 
-rbenv rehash
-rbenv global $LATEST_RUBY 
+  brew install vim
 
-brew install vim
-
-# dep for ghi
-gem install pygments.rb
-gem install bundler
-
-brew install ${cmds[@]} || { echo 'brew failed' ; exit 1; }
+  brew install ${cmds[@]} || { echo 'brew failed' ; exit 1; }
+fi
 
 # ==============================================
 # github
 # ==============================================
 
-git config --global user.name "Frederik Dudzik"
-git config --global user.email "$EMAIL"
-git config --global push.default simple
-git config --global core.editor vim
-git config --global credential.helper osxkeychain
-git config --global core.excludesfile ~/.gitignore_osx
-git config --global include.path ~/.gitaliases
-git config --global push.default current
-ssh-keygen -t rsa -b 4096 -C "$EMAIL"
-eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa
-cat ~/.ssh/id_rsa.pub | pbcopy
+if [ "$ALL" == true ] ; then
+  git config --global user.name "Frederik Dudzik"
+  git config --global user.email "$EMAIL"
+  git config --global push.default simple
+  git config --global core.editor vim
+  git config --global credential.helper osxkeychain
+  git config --global core.excludesfile ~/.gitignore_osx
+  git config --global include.path ~/.gitaliases
+  git config --global push.default current
+  ssh-keygen -t rsa -b 4096 -C "$EMAIL"
+  eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa
+  cat ~/.ssh/id_rsa.pub | pbcopy
 
-# echo in red
-tput setaf 1
-echo 'copied key to clipboard. opening github settings.'
-# stop echoing in red
-tput sgr0
+  # echo in red
+  tput setaf 1
+  echo 'copied key to clipboard. opening github settings.'
+  # stop echoing in red
+  tput sgr0
 
-echo 'Press [Enter] key when added key to github'
-sleep 2
-open https://github.com/settings/ssh
-read -p ''
-echo "ghi"
-ghi config --auth doodzik
+  echo 'Press [Enter] key when added key to github'
+  sleep 2
+  open https://github.com/settings/ssh
+  read -p ''
 
-# setup repo for dotfiles
-git init
-git remote add origin https://github.com/doodzik/dotfiles.git
-git fetch
-git checkout -t origin/master
-git submodule update --init --recursive --remote
+  # setup repo for dotfiles
+  git init
+  git remote add origin https://github.com/doodzik/dotfiles.git
+  git fetch
+  git checkout -t origin/master
+  git submodule update --init --recursive --remote
 
-cd .zprezto
-git submodule update --init --recursive --remote
+  cd .zprezto
+  git submodule update --init --recursive --remote
 
-echo "GitHub: When you are asked for your username and password. Enter your username, then in the password prompt paste your Personal Access Token from your password manager."
+  echo "GitHub: When you are asked for your username and password. Enter your username, then in the password prompt paste your Personal Access Token from your password manager."
 
-cd
+  cd
 
-cd .vim 
-./install
-cd
-
-# ==============================================
-# Zsh
-# ==============================================
-
-touch ~/.zshrc
-/usr/local/bin/zsh
-rm ~/.zshrc
-
-# Create a new Zsh configuration by copying the Zsh configuration files provided:
-setopt EXTENDED_GLOB
-for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
-  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
-done
-
-# set brew zsh as default shell
-echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
-chsh -s /usr/local/bin/zsh
+  cd .vim 
+  ./install
+  cd
+fi
 
 # ==============================================
 # nvm
 # ==============================================
 
-# setup node
-mkdir ~/.nvm
-. $(brew --prefix nvm)/nvm.sh
-nvm install 6
-nvm use 6
-nvm alias default 6
+if [ "$ALL" == true ] ; then
+  # setup node
+  mkdir ~/.nvm
+  . $(brew --prefix nvm)/nvm.sh
+  nvm install node
+  nvm alias default node
+  nvm use node
+fi
 
 # ==============================================
 # Xcode
 # ==============================================
-echo "Setting Xcode preferences"
 
-# Always use spaces for indenting
-defaults write com.apple.dt.Xcode DVTTextIndentUsingTabs -bool false
+if [ "$ALL" == true ] ; then
+  echo "Setting Xcode preferences"
 
-# Show tab bar
-defaults write com.apple.dt.Xcode AlwaysShowTabBar -bool true
+  # Always use spaces for indenting
+  defaults write com.apple.dt.Xcode DVTTextIndentUsingTabs -bool false
+
+  # Show tab bar
+  defaults write com.apple.dt.Xcode AlwaysShowTabBar -bool true
+fi
 
 # =============================================
 # GUI
 # =============================================
 
-echo "installing gui..."
+if [[ "$ALL" == true ]] || [[ "$GUI" == true ]]; then
 
-guis=(
-  vlc
-  anki
-  iterm2
-  fastlane
-)
+  echo "installing gui..."
 
-brew cask install ${guis[@]}
+  guis=(
+    vlc
+    iterm2
+    fastlane
+  )
 
-echo 'setup icloud && opening apps'
-echo 'trackpad tap to click & look up with 3 fingers'
-echo 'spaces: disable Automatically rearrange Spaces based on most recent use'
-echo 'Press [Enter] if done'
-sleep 2
-open -a System\ Preferences
-open -a Anki
+  brew cask install ${guis[@]}
 
-osascript -e '
-   on run
-        do shell script "echo setup assistive access for the terminal"
-   end run'
-read -p ''
+  echo 'setup icloud && opening apps'
+  echo 'trackpad tap to click & look up with 3 fingers'
+  echo 'spaces: disable Automatically rearrange Spaces based on most recent use'
+  echo 'Press [Enter] if done'
+  sleep 2
+  open -a System\ Preferences
 
-# =============================================
-# Safari
-# =============================================
-
-echo "setting up safari..."
-
-open "https://www.ublock.org"
-open "https://github.com/guyht/vimari/releases/latest"
-open "http://www.bumblebeesystems.com/wastenotime/"
-
-open "https://ankiweb.net/shared/info/3448800906"
-open "https://ankiweb.net/shared/info/1600138415"
-open "https://ankiweb.net/shared/info/315734179"
-
-open "http://www.remotemouse.net"
-open "http://www.wacom.com/en-us/support/product-support/drivers"
-open "http://magnet.crowdcafe.com/#download"
-
-echo "set ublock eu cookie warning"
-echo "import waste no time config"
-echo "wacom desktop login and reset settings"
-echo "disable wacom desktop autostart. In the menu bar settings."
-echo "press [enter] to continue"
-read -p ''
-
-# enable safari dev mode
-defaults write com.apple.Safari WebKitDeveloperExtras -bool true
-
-osascript -e 'tell application "Safari" to activate
-                delay 3
-                tell application "System Events" to tell process "Safari"
-                  keystroke "," using command down
-
-                  tell group 1 of group 1 of window 1
-                      tell pop up button 6
-                        click
-                        click menu item "After one week" of menu 1
-                      end tell
-                  end tell
-              end tell'
-
+  osascript -e '
+     on run
+          do shell script "echo setup assistive access for the terminal"
+     end run'
+  read -p ''
+fi
 
 # ==============================================
 # system
@@ -223,71 +188,76 @@ osascript -e 'tell application "Safari" to activate
 # monitor changes to the settings
 # sudo opensnoop -n cfprefsd-int-int
 
-# disable gateskeeper
-m gatekeeper disable
+if [[ "$ALL" == true ]] || [[ "$SYSTEM" == true ]]; then
+  # disable gateskeeper
+  m gatekeeper disable
 
-# multitouch/trackpad
-defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerTapGesture -int 2;
-defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1;
-defaults write -g com.apple.trackpad.scaling 3
+  # multitouch/trackpad
+  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerTapGesture -int 2;
+  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1;
+  defaults write -g com.apple.trackpad.scaling 3
 
-# keyboard
-defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '{ InputSourceKind = "Keyboard Layout"; "KeyboardLayout ID" = 0; "KeyboardLayout Name" = "U.S"; }'
-defaults write InitialKeyRepeat -int 15
-defaults write KeyRepeat -int 2
+  # keyboard
+  defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '{ InputSourceKind = "Keyboard Layout"; "KeyboardLayout ID" = 0; "KeyboardLayout Name" = "U.S"; }'
+  defaults write InitialKeyRepeat -int 15
+  defaults write KeyRepeat -int 2
 
-# capslock to cntr
-# ~/Library/Preferences/ByHost/.GlobalPreferences
-mappingplist=com.apple.keyboard.modifiermapping.1452-585-0
-defaults -currentHost write -g $mappingplist '({
-    HIDKeyboardModifierMappingDst = 2;
-    HIDKeyboardModifierMappingSrc = 0;
-  })'
+  # capslock to cntr
+  # ~/Library/Preferences/ByHost/.GlobalPreferences
+  mappingplist=com.apple.keyboard.modifiermapping.1452-585-0
+  defaults -currentHost write -g $mappingplist '({
+      HIDKeyboardModifierMappingDst = 2;
+      HIDKeyboardModifierMappingSrc = 0;
+    })'
 
-# notification settings - apple killed that config
-# launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
-# killall NotificationCenter
+  # menu bar
+  defaults read com.apple.menuextra.battery ShowPercent -bool YES
 
-# menu bar
-defaults read com.apple.menuextra.battery ShowPercent -bool YES
+  # users
+  defaults write com.apple.loginwindow GuestEnabled -bool NO
+  defaults write com.apple.loginwindow SHOWFULLNAME -int 1
 
-# users
-defaults write com.apple.loginwindow GuestEnabled -bool NO
-defaults write com.apple.loginwindow SHOWFULLNAME -int 1
+  # dock
+  m dock autohide YES
+  defaults write com.apple.dock mineffect -string 'scale'
+  defaults write com.apple.dock persistent-apps '()'
 
-# dock
-m dock autohide YES
-defaults write com.apple.dock mineffect -string 'scale'
-defaults write com.apple.dock persistent-apps '()'
+  # finder
+  m finder showhiddenfiles YES
+  m finder showextensions YES
 
-# finder
-m finder showhiddenfiles YES
-m finder showextensions YES
+  # Don't offer new disks for backup
+  defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
 
-# Don't offer new disks for backup
-defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
+  # symlink iCloud Folder to ~/
+  ln -s Library/Mobile\ Documents/com~apple~CloudDocs
+  mv com\~apple\~CloudDocs iCloud
 
-# disable desktop
-defaults write com.apple.finder CreateDesktop -bool FALSE
+  # symbolic hotkeys
+  # Select the previous input source - Command, Option, Space
+  defaults write ~/Library/Preferences/com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add 60 "{ enabled = 1; value = { parameters = ( 32, 49, 262144 ); type = standard; }; }"
 
-# change screenshot folder
-defaults write com.apple.screencapture location ~/Downloads
+  # no blurry font
+  defaults write com.apple.Terminal AppleFontSmoothing -int 0
 
-# symlink iCloud Folder to ~/
-ln -s Library/Mobile\ Documents/com~apple~CloudDocs
-mv com\~apple\~CloudDocs iCloud
+  RESTART=true
+fi
 
-# symbolic hotkeys
-# Select the previous input source - Command, Option, Space
-defaults write ~/Library/Preferences/com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add 60 "{ enabled = 1; value = { parameters = ( 32, 49, 262144 ); type = standard; }; }"
+# ==============================================
+# Zsh
+# ==============================================
 
-# no blurry font
-defaults write com.apple.Terminal AppleFontSmoothing -int 0
+if [ "$ALL" == true ] ; then
+  $HOME/.init_zsh
+fi
 
 # ==============================================
 # restart
 # ==============================================
 
-echo 'Press [Enter] to restart the computer'
-read -p ''
-m restart
+if [ "$RESTART" = true ] ; then
+  echo 'Press [Enter] to restart the computer'
+  read -p ''
+  m restart
+fi
+
